// <auto-generated />
using MVC_Basics_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_Basics_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211204211640_Seed more data")]
    partial class Seedmoredata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_Basics_1.Models.CityModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CountryCode");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryCode = "SWE",
                            Name = "Vänersborg",
                            Population = 39606
                        },
                        new
                        {
                            ID = 2,
                            CountryCode = "SWE",
                            Name = "Göteborg",
                            Population = 1060000
                        },
                        new
                        {
                            ID = 3,
                            CountryCode = "SWE",
                            Name = "Stockholm",
                            Population = 1657000
                        },
                        new
                        {
                            ID = 4,
                            CountryCode = "SWE",
                            Name = "Trollhättan",
                            Population = 54487
                        },
                        new
                        {
                            ID = 5,
                            CountryCode = "GBR",
                            Name = "London",
                            Population = 961989
                        },
                        new
                        {
                            ID = 6,
                            CountryCode = "USA",
                            Name = "Washington D.C.",
                            Population = 689545
                        });
                });

            modelBuilder.Entity("MVC_Basics_1.Models.CountryModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "GHA",
                            Continent = "Africa",
                            Name = "Ghana",
                            Population = 20212000
                        },
                        new
                        {
                            Code = "GBR",
                            Continent = "Europe",
                            Name = "United Kingdom",
                            Population = 59623400
                        },
                        new
                        {
                            Code = "SWE",
                            Continent = "Europe",
                            Name = "Sweden",
                            Population = 10188382
                        },
                        new
                        {
                            Code = "USA",
                            Continent = "North America",
                            Name = "United States",
                            Population = 278357000
                        });
                });

            modelBuilder.Entity("MVC_Basics_1.Models.LanguageModel", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageID = 1,
                            Description = "The international language spoken by many people around the world",
                            Name = "English"
                        },
                        new
                        {
                            LanguageID = 2,
                            Description = "The  second international language spoken by in the different region of the world",
                            Name = "Arabic"
                        },
                        new
                        {
                            LanguageID = 3,
                            Description = "The main language spoken in the Sweden Country",
                            Name = "Swedish"
                        });
                });

            modelBuilder.Entity("MVC_Basics_1.Models.PeopleModel", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("CityID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            CityID = 1,
                            Email = "ekram234@gmail.com",
                            FullName = "Ekram Ahmedin",
                            PhoneNumber = "0791234567"
                        },
                        new
                        {
                            PersonId = 2,
                            CityID = 2,
                            Email = "timsnds241@gmail.com",
                            FullName = "Eve Andersson",
                            PhoneNumber = "+46701297530"
                        },
                        new
                        {
                            PersonId = 3,
                            CityID = 1,
                            Email = "ulf78s3@hotmail.com",
                            FullName = "Ulf David",
                            PhoneNumber = "0752875207"
                        },
                        new
                        {
                            PersonId = 4,
                            CityID = 4,
                            Email = "alimuhammed@gmail.com",
                            FullName = "Ali Muhammed",
                            PhoneNumber = "0796078542"
                        },
                        new
                        {
                            PersonId = 5,
                            CityID = 3,
                            Email = "mariaSvensson234@gmail.com",
                            FullName = "Maria Svensson",
                            PhoneNumber = "+46791028376"
                        },
                        new
                        {
                            PersonId = 6,
                            CityID = 3,
                            Email = "RahwaSuliman1234@gmail.com",
                            FullName = "Rahwa Suliman",
                            PhoneNumber = "0764933276"
                        });
                });

            modelBuilder.Entity("MVC_Basics_1.Models.People_LanguageModel", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "LanguageID");

                    b.HasIndex("LanguageID");

                    b.ToTable("PeopleLanguages");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            LanguageID = 3
                        },
                        new
                        {
                            PersonId = 1,
                            LanguageID = 2
                        },
                        new
                        {
                            PersonId = 1,
                            LanguageID = 1
                        },
                        new
                        {
                            PersonId = 2,
                            LanguageID = 3
                        },
                        new
                        {
                            PersonId = 2,
                            LanguageID = 1
                        },
                        new
                        {
                            PersonId = 3,
                            LanguageID = 3
                        },
                        new
                        {
                            PersonId = 4,
                            LanguageID = 2
                        });
                });

            modelBuilder.Entity("MVC_Basics_1.Models.CityModel", b =>
                {
                    b.HasOne("MVC_Basics_1.Models.CountryModel", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC_Basics_1.Models.PeopleModel", b =>
                {
                    b.HasOne("MVC_Basics_1.Models.CityModel", "City")
                        .WithMany("People")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC_Basics_1.Models.People_LanguageModel", b =>
                {
                    b.HasOne("MVC_Basics_1.Models.LanguageModel", "Language")
                        .WithMany("PeopleLanguages")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Basics_1.Models.PeopleModel", "People")
                        .WithMany("PeopleLanguages")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
